# Site settings
title: "Seven' Resume"
description: "Powered by Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Seven | 陈 浩"
resume_title:                   "Let's make the internet better!"
resume_contact_email:           "askdaddy@gmail.com"
resume_contact_telephone:       "18616304029"
resume_contact_address:         "保密 =）"
resume_header_contact_info: "18616304029 | askdaddy@gmail.com"
resume_header_intro: "<p>后端研发，DevOps，Windows&Android研发，持续创业者。</p>"
# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       false
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/askdaddy"
  resume_twitter_url:           "http://twitter.com/humen1"
  #resume_dribbble_url:          "https://"
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://humen1.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
